### ISSUE TITLE
Socket ssl wrapping error: [Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by alsigit** [zblurx/certsync#3]
Hi, I got this error:
[*] Collecting userlist, CA info and CRL on LDAP
[-] Got error: socket ssl wrapping error: [Errno 54] Connection reset by peer
[-] Use -debug to print a stacktrace

This is when I use - debug
[-] Got error: socket ssl wrapping error: [Errno 54] Connection reset by peer
Traceback (most recent call last):
  File "/Users/test/.pyenv/versions/3.7.13/lib/python3.7/site-packages/certipy/lib/ldap.py", line 77, in connect
    self.connect(version=ssl.PROTOCOL_TLSv1_2)
  File "/Users/test/.pyenv/versions/3.7.13/lib/python3.7/site-packages/certipy/lib/ldap.py", line 128, in connect
    bind_result = ldap_conn.bind()
  File "/Users/test.pyenv/versions/3.7.13/lib/python3.7/site-packages/ldap3/core/connection.py", line 589, in bind
    self.open(read_server_info=False)
  File "/Users/test/.pyenv/versions/3.7.13/lib/python3.7/site-packages/ldap3/strategy/sync.py", line 57, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/Users/test/.pyenv/versions/3.7.13/lib/python3.7/site-packages/ldap3/strategy/base.py", line 146, in open
    raise exception_history[0][0]
ldap3.core.exceptions.LDAPSocketOpenError: socket ssl wrapping error: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/test/.pyenv/versions/3.7.13/lib/python3.7/site-packages/certsync/entry.py", line 602, in main
    certsync.run()
  File "/Users/test/.pyenv/versions/3.7.13/lib/python3.7/site-packages/certsync/entry.py", line 169, in run
    self.init_ldap_conn()
  File "/Users/test/.pyenv/versions/3.7.13/lib/python3.7/site-packages/certsync/entry.py", line 161, in init_ldap_conn
    self.ldap_connection.connect()
  File "/Users/test/.pyenv/versions/3.7.13/lib/python3.7/site-packages/certipy/lib/ldap.py", line 83, in connect
    self.connect(version=ssl.PROTOCOL_TLSv1)
  File "/Users/test/.pyenv/versions/3.7.13/lib/python3.7/site-packages/certipy/lib/ldap.py", line 128, in connect
    bind_result = ldap_conn.bind()
  File "/Users/test/.pyenv/versions/3.7.13/lib/python3.7/site-packages/ldap3/core/connection.py", line 589, in bind
    self.open(read_server_info=False)
  File "/Users/test/.pyenv/versions/3.7.13/lib/python3.7/site-packages/ldap3/strategy/sync.py", line 57, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/Users/test/.pyenv/versions/3.7.13/lib/python3.7/site-packages/ldap3/strategy/base.py", line 146, in open
    raise exception_history[0][0]
ldap3.core.exceptions.LDAPSocketOpenError: socket ssl wrapping error: [Errno 54] Connection reset by peer

Is this issue caused by firewall?
Thank you.

**Comment by zblurx** [comment]
Hey, can i get the command with arguments ? My guess is that your DC does not support LDAPS, and if so you should add to your command `-scheme ldap` in order to enforce communication over LDAP

**Comment by alsigit** [comment]
my command  just like this:
certsync -u username -p 'password' -d domain -dc-ip 10.x.x.x -ns 10.x.x.x

update:
I add -scheme ldap 
[*] Collecting userlist, CA info and CRL on LDAP
[-] Got error: Failed to authenticate to LDAP. Invalid credentials
[-] Use -debug to print a stacktrace

**Comment by zblurx** [comment]
Can you send your full command with `-debug` and `-scheme ldap`, and the full result ? The SSL problem seems to be resolved, but you might  have entered invalid credentials.

**Comment by zblurx** [comment]
Closing now
